### ISSUE TITLE
[localize] Provide Firefox Voice in other languages

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1015]
This is a meta bug, listing tickets in the order I think they should be tackled:

- [ ] Create language preference setting #1010
- [ ] Localize language/compiler #1012
- [ ] Create localized phrase definitions #1013
- [ ] Localize text output #1011
- [ ] Setup Pontoon for Firefox Voice #1014
- [ ] Find and fix English-oriented services #1009
