### ISSUE TITLE
[wakeword] Enable wakeword

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1037]
This is a meta ticket for doing a wakeword:

- [ ] Wakeword pref change doesn't always start recorder · Issue #1036
- [ ] Don't enable wakeword when there's no specific word · Issue #943 
- [ ] [Settings] Design for enable wakeword · Issue #986
- [ ] Open recorder page when wakeword is active · Issue #947 
- [ ] [wakeword] Show wakeword indicator · Issue #944

And some optional tickets:

- [ ] [wakeword] Raise window when wakeword is given · Issue #950
