### ISSUE TITLE
Refactorings

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1600]
Some things that would be nice to do:

- [ ] Simplify content script loading
- [x] Get rid of some helpers in IntentContext, use browserUtils directly instead #1764
- [x] Move `background/language/` up a directory (has no background-specific code) #1766
- [ ] Move some built files into clearer locations (e.g., `build/`):
  - [ ] `background/intentImport.js`
  - [x] All files generated from `.jsx` (decided not to do this)
- [x] Rename either `language/matching.js` or `language/textMatching.js` #1769
- [ ] Rename `language/langs/lang.js` (to `languageList.js`?) Do we even need this?
- [x] Make sure all generated files indicate what they are generated by (in a comment)
- [x] Simplify `moduleLoader.js` and`loadMain.js` #1768
- [ ] Name content scripts consistently
- [ ] Maybe rename `catcherAsyncSetup.js`
- [ ] Get rid of giant if/else in `main.js` (use registration)
- [ ] Refactor and trim down `background/content/helpers.js`
- [x] Rename `lazyInject()` #1763
- [ ] Remove duplication between `clipboard` and `saving` intents
- [ ] Rename `find` intent
- [ ] Rename `nicknames` to `routines`
- [ ] Figure out or remove `extension/js/languages.json`
- [x] Remove polyfill code #1767
- [ ] Normalize names in `bin/` a bit
- [ ] Decide if intent-viewer.html is worth it
- [ ] Generate the code layout in `docs/architecture.md` from comments
- [x] Rename any `run(desc)` to `run(context)` #1765

**Comment by ianb** [comment]
I'd like to still do:

- Fix content scripts (#1085)
- Organize messages some (#1804)
- Rename nicknames (#1805)

But the rest I don't think is worth it.
